services:
  mongodb:
    image: mongo
    container_name: 'mongodb'
    ports:
      - '27017:27017'
    #volumes:
    #  - data:/data/db
    env_file:
      - ./env/mongo.env
  redis:
    image: redis
    container_name: 'redis'
    ports:
      - '6379:6379'
  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./env/backend.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
    depends_on:
      - mongodb
    container_name: backend
  frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    env_file:
      - ./env/frontend.env
    stdin_open: true
    tty: true
    depends_on:
      - backend
    container_name: frontend
#volumes:
#  data: