services:
  mongodb:
    image: mongo
    container_name: 'mongodb'
    ports:
      - '27017:27017'
    #volumes:
    #  - data:/data/db
    env_file:
      - ./env/mongo.env
  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./env/backend.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/public:/app/public
    depends_on:
      - mongodb
    container_name: backend
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend/src:/app/src
  #     - /app/node_modules
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend
  #   container_name: goals-frontend
#volumes:
#  data: